"""Built-in concept knowledge used by the offline heuristic analyst.

When an LLM key is configured, concepts are explained by the model instead;
this library guarantees the Concept Tutor works with zero external services.
Keys are lowercase match phrases; a concept fires when any phrase appears in a segment.
"""

CONCEPTS: dict[str, dict] = {
    "oauth": {
        "term": "OAuth 2.0",
        "category": "security",
        "what": "An open standard that lets an app access a user's data on another service without ever seeing the user's password. The user approves access and the app receives a scoped, revocable access token.",
        "why_matters": "It is the backbone of 'Sign in with Google/GitHub' and of most service-to-service authorization. Getting it wrong is a top cause of security incidents.",
        "beginner": "Think of a hotel key card: the front desk (identity provider) checks your ID once and gives you a card that opens only your room, only for your stay. Apps get 'key cards' (tokens) instead of your password.",
        "advanced": "Core flows: Authorization Code + PKCE for user-facing apps, Client Credentials for machine-to-machine. Tokens are usually JWTs; refresh tokens extend sessions. Watch scope design, token lifetime, rotation, and redirect-URI validation.",
        "analogy": "A valet key that starts the car but won't open the trunk.",
        "pitfalls": "Storing tokens in localStorage (XSS risk), overly broad scopes, skipping PKCE, treating OAuth (authorization) as authentication — that's OpenID Connect's job.",
        "related": ["JWT", "OpenID Connect", "PKCE", "SSO"],
    },
    "jwt": {
        "term": "JWT (JSON Web Token)",
        "category": "security",
        "what": "A compact, signed token containing JSON claims (who you are, what you can do, when it expires). Servers verify the signature instead of hitting a session store.",
        "why_matters": "Enables stateless auth across microservices — any service can verify identity locally.",
        "beginner": "A tamper-proof wristband from a festival: anyone can read it, nobody can forge it, and it expires.",
        "advanced": "Header.payload.signature, base64url-encoded. Prefer asymmetric signing (RS256/ES256) so services verify with a public key. Keep TTLs short; pair with refresh tokens. Revocation requires a denylist or short expiry.",
        "analogy": "A signed hall pass.",
        "pitfalls": "Putting secrets in the payload (it's only encoded, not encrypted), accepting alg=none, long-lived tokens with no revocation path.",
        "related": ["OAuth 2.0", "Session management", "Signing keys"],
    },
    "redis": {
        "term": "Redis",
        "category": "infrastructure",
        "what": "An in-memory data store used as a cache, message broker, and fast key-value database. Sub-millisecond reads because data lives in RAM.",
        "why_matters": "The default answer to 'this endpoint is slow' and 'we need shared state across servers' — caching, sessions, rate limiting, queues, pub/sub.",
        "beginner": "A sticky note on your monitor versus a filing cabinet (the database). Much faster to read, but limited space and it can be wiped.",
        "advanced": "Single-threaded event loop; rich types (hashes, sorted sets, streams). Persistence via RDB snapshots/AOF. Scale with Cluster (sharding) and replicas. Define eviction policy (e.g. allkeys-lru) and cache invalidation strategy explicitly.",
        "analogy": "Short-term memory for your system.",
        "pitfalls": "Treating it as the source of truth, unbounded keys without TTLs, hot keys, cache stampedes on expiry.",
        "related": ["Caching", "Pub/Sub", "Memcached", "Rate limiting"],
    },
    "kafka": {
        "term": "Apache Kafka",
        "category": "infrastructure",
        "what": "A distributed event streaming platform. Producers append events to durable, ordered logs (topics); many consumers read at their own pace.",
        "why_matters": "Decouples systems: services publish facts ('order placed') without knowing who consumes them. Powers event-driven architecture, analytics pipelines, and audit logs.",
        "beginner": "A newspaper: reporters (producers) publish stories to sections (topics); every subscriber (consumer) reads their own copy at their own pace, and back issues stay available.",
        "advanced": "Topics split into partitions for parallelism; ordering only within a partition — partition keys matter. Consumer groups share work and track offsets. Delivery is at-least-once by default; exactly-once needs idempotent producers + transactions.",
        "analogy": "A durable, replayable company-wide announcement board.",
        "pitfalls": "Poor partition key choice (hot partitions, broken ordering), unbounded consumer lag, using it as a database or for request/response RPC.",
        "related": ["Event-driven architecture", "Pub/Sub", "Event sourcing", "Message queues"],
    },
    "kubernetes": {
        "term": "Kubernetes",
        "category": "infrastructure",
        "what": "A container orchestrator: you declare the desired state (run 5 copies of this service, with these resources) and it continuously schedules, heals, and scales containers across machines.",
        "why_matters": "The industry standard for running production services — deployments, rollbacks, autoscaling, and self-healing come standard.",
        "beginner": "An air-traffic controller for your apps: it decides which runway (machine) each plane (container) uses, and if one crashes it launches a replacement automatically.",
        "advanced": "Pods are the unit of scheduling; Deployments manage replica sets and rolling updates; Services/Ingress handle networking; ConfigMaps/Secrets carry config. The reconciliation loop drives actual state toward declared state.",
        "analogy": "A thermostat for infrastructure — declare the temperature, it does the work.",
        "pitfalls": "Missing resource requests/limits (noisy neighbors, OOMKills), no liveness/readiness probes, treating pods as pets instead of cattle.",
        "related": ["Docker", "Containers", "Helm", "Service mesh"],
    },
    "terraform": {
        "term": "Terraform",
        "category": "infrastructure",
        "what": "Infrastructure as Code: cloud resources (servers, databases, DNS) are declared in files, and Terraform computes and applies the changes needed to make reality match.",
        "why_matters": "Infrastructure becomes reviewable, versioned, and reproducible — no more hand-built 'snowflake' environments.",
        "beginner": "A recipe for your cloud: instead of clicking around the AWS console, you write down what you want and Terraform 'cooks' it, identically, every time.",
        "advanced": "State files map declarations to real resources — store remotely with locking. plan shows the diff before apply. Modules enable reuse; workspaces separate environments. Drift happens when people change things manually.",
        "analogy": "Blueprints plus a construction crew.",
        "pitfalls": "Local/uncommitted state, manual console edits causing drift, giant single-state monoliths, secrets in state files.",
        "related": ["Infrastructure as Code", "Pulumi", "CloudFormation", "GitOps"],
    },
    "rag": {
        "term": "RAG (Retrieval-Augmented Generation)",
        "category": "ai",
        "what": "A pattern where an LLM's prompt is augmented with relevant documents fetched at query time (usually via vector search), so answers are grounded in your data instead of only training data.",
        "why_matters": "The standard way to give AI access to private, current knowledge (docs, tickets, code) without retraining, and to reduce hallucination.",
        "beginner": "An open-book exam instead of a closed-book one: the model gets to look up the relevant pages before answering.",
        "advanced": "Pipeline: chunk → embed → index → retrieve (dense + keyword hybrid) → rerank → generate with citations. Quality hinges on chunking strategy, retrieval recall, and prompt construction; evaluate retrieval and generation separately.",
        "analogy": "A librarian who pulls the right three books before the expert answers.",
        "pitfalls": "Bad chunking (split tables, lost context), retrieving irrelevant text that poisons answers, no citations, stale indexes.",
        "related": ["Vector database", "Embeddings", "Semantic search", "LLM"],
    },
    "vector database": {
        "term": "Vector database",
        "category": "ai",
        "what": "A database that stores embeddings (lists of numbers representing meaning) and finds the nearest neighbors of a query vector — i.e., search by meaning rather than exact keywords.",
        "why_matters": "The retrieval backbone of RAG, semantic search, and recommendations. 'Find things like this' becomes a database query.",
        "beginner": "A library organized by topic-similarity instead of alphabetically: books about similar ideas sit on nearby shelves, so you find related material even if titles share no words.",
        "advanced": "ANN indexes (HNSW, IVF) trade recall for speed. Choose metric (cosine/dot/L2) to match the embedding model. Hybrid search (vector + BM25) plus metadata filtering usually beats pure vector. Examples: pgvector, Pinecone, Qdrant, Weaviate.",
        "analogy": "GPS coordinates for ideas — nearby points mean similar meanings.",
        "pitfalls": "Mixing embeddings from different models in one index, skipping metadata filters, assuming semantic search always beats keyword search.",
        "related": ["Embeddings", "RAG", "pgvector", "Semantic search"],
    },
    "embedding": {
        "term": "Embeddings",
        "category": "ai",
        "what": "Numeric representations of text (or images, audio) where similar meanings land close together in vector space. Produced by neural models.",
        "why_matters": "They let software compare meaning: search, clustering, deduplication, recommendations, RAG retrieval.",
        "beginner": "Every sentence gets coordinates on a giant map of meaning; 'car' and 'automobile' end up neighbors even though the words differ.",
        "advanced": "Dimensionality typically 256–3072. Cosine similarity is the usual metric. Domain mismatch degrades quality; chunk size affects retrieval granularity. Never compare vectors across different models.",
        "analogy": "Latitude/longitude for concepts.",
        "pitfalls": "Comparing embeddings from different models, embedding huge chunks (meaning gets averaged away), ignoring normalization.",
        "related": ["Vector database", "RAG", "Semantic search"],
    },
    "microservice": {
        "term": "Microservices",
        "category": "architecture",
        "what": "An architecture where the system is split into small, independently deployable services, each owning one business capability and its own data.",
        "why_matters": "Lets many teams ship independently and scale hot paths separately — at the cost of distributed-systems complexity.",
        "beginner": "A food court instead of one giant restaurant: each stall has its own kitchen and menu, so one closing doesn't shut down lunch.",
        "advanced": "Key decisions: service boundaries (align with domains — DDD), sync REST/gRPC vs async events, data ownership per service, sagas instead of distributed transactions, and observability (tracing) as a first-class concern.",
        "analogy": "Specialized departments with clear contracts instead of one department that does everything.",
        "pitfalls": "The 'distributed monolith' (services that must deploy together), shared databases, network calls treated as free, premature adoption before the domain is understood.",
        "related": ["API gateway", "Event-driven architecture", "Service mesh", "Domain-driven design"],
    },
    "opentelemetry": {
        "term": "OpenTelemetry",
        "category": "observability",
        "what": "A vendor-neutral standard and SDK for emitting traces, metrics, and logs from applications, so you can see what happened across services for any request.",
        "why_matters": "In distributed systems, 'why was this request slow?' is unanswerable without tracing. OTel decouples instrumentation from the backend (Datadog, Grafana, Honeycomb...).",
        "beginner": "A tracking number for every request: as it moves through your services, each stop stamps it, so you can see the whole journey and where it got stuck.",
        "advanced": "Traces = spans with parent/child links propagated via context headers (W3C traceparent). The Collector receives, processes, and exports telemetry. Sampling (head vs tail) controls cost. Auto-instrumentation covers common frameworks.",
        "analogy": "Package tracking for requests.",
        "pitfalls": "No context propagation across queues, 100% sampling cost surprises, high-cardinality metric labels.",
        "related": ["Distributed tracing", "Observability", "Prometheus", "Jaeger"],
    },
    "fastify": {
        "term": "Fastify",
        "category": "framework",
        "what": "A high-performance Node.js web framework with schema-based validation and a plugin architecture — a faster, more structured alternative to Express.",
        "why_matters": "Teams pick it for throughput (JSON serialization is compiled from schemas) and built-in validation/typing discipline.",
        "beginner": "Like Express (the classic Node web framework) but with a stricter, faster engine: you declare what requests/responses look like and it validates them for you.",
        "advanced": "JSON Schema per route drives validation and fast-json-stringify serialization. Encapsulated plugin contexts prevent global soup. First-class TypeScript and hooks (onRequest, preHandler...) for middleware-style logic.",
        "analogy": "Express with a turbocharger and a seatbelt.",
        "pitfalls": "Skipping response schemas (losing the speed benefit), fighting plugin encapsulation, assuming Express middleware works unchanged.",
        "related": ["Node.js", "Express", "NestJS", "JSON Schema"],
    },
    "graphql": {
        "term": "GraphQL",
        "category": "api",
        "what": "A query language for APIs: clients ask for exactly the fields they need in one request, and the server resolves them against a typed schema.",
        "why_matters": "Kills over-fetching/under-fetching and round-trip waterfalls, especially for mobile and complex UIs.",
        "beginner": "Ordering à la carte instead of a fixed menu: you list exactly the dishes (fields) you want and get precisely that, in one order.",
        "advanced": "Single endpoint; schema-first typing; resolvers per field (beware N+1 — use DataLoader batching). Mutations for writes, subscriptions for realtime. Caching and rate limiting need query-cost analysis rather than URL-based rules.",
        "analogy": "A personal shopper for data.",
        "pitfalls": "N+1 resolver queries, unbounded query depth/complexity from untrusted clients, losing HTTP caching semantics.",
        "related": ["REST", "Apollo", "API gateway", "Schema design"],
    },
    "rate limit": {
        "term": "Rate limiting",
        "category": "architecture",
        "what": "Restricting how many requests a client can make in a time window, to protect services from overload and abuse.",
        "why_matters": "Without it, one buggy client or attacker can take down an API for everyone. Also enforces fair usage tiers.",
        "beginner": "A bouncer with a counter: each guest gets N entries per hour; after that they wait outside until the hour resets.",
        "advanced": "Algorithms: token bucket (allows bursts), sliding window, leaky bucket. Enforce at the gateway with shared state (often Redis). Return 429 + Retry-After. Decide the key: per user, per API key, per IP.",
        "analogy": "A turnstile that only spins so fast.",
        "pitfalls": "Per-instance counters that break behind load balancers, limiting by IP behind NATs, no client backoff guidance.",
        "related": ["API gateway", "Redis", "Backpressure", "DDoS protection"],
    },
    "optimistic concurrency": {
        "term": "Optimistic concurrency control",
        "category": "architecture",
        "what": "A strategy where writers don't lock data; instead each update checks 'has this changed since I read it?' (via a version number) and retries if someone else got there first.",
        "why_matters": "Locks kill throughput and cause deadlocks. When conflicts are rare, optimistic control gives high concurrency with correctness.",
        "beginner": "Two people editing the same wiki page: instead of locking the page, the site accepts the first save and tells the second person 'the page changed — review and resubmit.'",
        "advanced": "Implemented with a version/timestamp column: UPDATE ... WHERE id=? AND version=?; zero rows affected means conflict → reload and retry. HTTP equivalent: ETag + If-Match (412 on mismatch). Contrast with pessimistic SELECT ... FOR UPDATE.",
        "analogy": "Saving a shared doc and being asked to merge if someone edited meanwhile.",
        "pitfalls": "Forgetting retry logic (users just see failures), high-contention rows causing retry storms, mixing optimistic and pessimistic access to the same data.",
        "related": ["Database transactions", "ETag", "Pessimistic locking", "Idempotency"],
    },
    "event sourcing": {
        "term": "Event sourcing",
        "category": "architecture",
        "what": "Storing every change as an immutable event ('OrderPlaced', 'ItemRemoved') instead of overwriting current state; state is rebuilt by replaying events.",
        "why_matters": "Gives a perfect audit trail, time travel, and natural integration with event-driven systems.",
        "beginner": "A bank ledger: your balance isn't stored as one editable number — it's the sum of every deposit and withdrawal ever recorded.",
        "advanced": "Append-only event store; projections build read models; snapshots bound replay cost. Usually paired with CQRS. Schema evolution of old events is the hard long-term problem.",
        "analogy": "Git for business data — history is the source of truth.",
        "pitfalls": "Using it everywhere (huge complexity tax), unversioned event schemas, eventual consistency surprising product teams.",
        "related": ["CQRS", "Kafka", "Audit logging", "Event-driven architecture"],
    },
    "feature flag": {
        "term": "Feature flags",
        "category": "delivery",
        "what": "Runtime switches that turn features on/off per user, percentage, or environment without deploying code.",
        "why_matters": "Decouples deploy from release: ship dark, roll out gradually, kill instantly if metrics regress. Enables A/B testing and trunk-based development.",
        "beginner": "Light switches for features: the wiring (code) is already installed everywhere, but you choose when and for whom to flip each switch.",
        "advanced": "Targeting rules (user, cohort, percentage with sticky bucketing), kill switches for risky paths, experiment integration. Flags are tech debt — track owners and expiry.",
        "analogy": "A dimmer switch for rollouts.",
        "pitfalls": "Dead flags accumulating for years, testing only flag-on paths, flag combinatorics exploding QA scope.",
        "related": ["Canary deployment", "A/B testing", "Trunk-based development", "LaunchDarkly"],
    },
    "websocket": {
        "term": "WebSockets",
        "category": "api",
        "what": "A persistent, two-way connection between browser and server over one TCP socket — either side can push messages at any time.",
        "why_matters": "The standard transport for real-time UIs: chat, live dashboards, collaborative editing, this very app's live meeting stream.",
        "beginner": "HTTP is sending letters (one request, one reply). A WebSocket is a phone call: the line stays open and both sides can talk whenever.",
        "advanced": "Starts as an HTTP Upgrade handshake. Needs heartbeats (ping/pong) to detect dead peers, reconnect-with-backoff on the client, and sticky sessions or a pub/sub backplane (Redis) when scaling to multiple servers.",
        "analogy": "An open phone line versus mailing letters.",
        "pitfalls": "No reconnection strategy, assuming ordered delivery across reconnects, load balancers killing idle connections.",
        "related": ["Server-Sent Events", "Long polling", "Socket.IO", "Redis pub/sub"],
    },
    "circuit breaker": {
        "term": "Circuit breaker",
        "category": "architecture",
        "what": "A resilience pattern: after repeated failures calling a dependency, stop calling it for a cooldown period and fail fast instead of piling up timeouts.",
        "why_matters": "Prevents cascade failures — one slow downstream service can otherwise exhaust every caller's threads and take down the whole system.",
        "beginner": "An electrical breaker: when a circuit is dangerous, it trips and cuts power instead of letting the house burn; later you can reset it and try again.",
        "advanced": "States: closed → open (on failure threshold) → half-open (probe requests) → closed. Combine with timeouts, retries with jitter, and bulkheads. Libraries: resilience4j, Polly; or service-mesh level.",
        "analogy": "A fuse for service calls.",
        "pitfalls": "Retrying into an open breaker, thresholds so high it never trips, no fallback path when open.",
        "related": ["Retries", "Bulkhead", "Timeouts", "Service mesh"],
    },
    "sso": {
        "term": "SSO (Single Sign-On)",
        "category": "security",
        "what": "One login grants access to many applications — a central identity provider (Okta, Entra ID, Google Workspace) vouches for the user to each app.",
        "why_matters": "Enterprise table stakes: IT controls access centrally, users keep one credential, offboarding is instant.",
        "beginner": "A wristband at a resort: check in once at the front desk, then every restaurant and pool accepts the wristband instead of asking for ID again.",
        "advanced": "Protocols: SAML 2.0 (XML, enterprise legacy) and OpenID Connect (OAuth-based, modern). SCIM handles user provisioning/deprovisioning. Per-tenant IdP config is the core of 'enterprise readiness'.",
        "analogy": "One master key, many doors.",
        "pitfalls": "Only supporting one IdP, ignoring SCIM (stale accounts), weak session logout across apps.",
        "related": ["OAuth 2.0", "SAML", "OpenID Connect", "SCIM"],
    },
    "postgres": {
        "term": "PostgreSQL",
        "category": "infrastructure",
        "what": "The leading open-source relational database: ACID transactions, rich SQL, JSON support, and extensions (pgvector, PostGIS) that stretch it far beyond tables.",
        "why_matters": "The default 'boring, correct' choice for a system's source of truth — and increasingly for vector search and queues too.",
        "beginner": "A meticulous librarian: everything filed in structured tables, every change recorded safely, and it can answer very complex questions about how records relate.",
        "advanced": "MVCC for concurrency (readers don't block writers), WAL for durability/replication, powerful indexing (B-tree, GIN, BRIN, HNSW via pgvector). Connection pooling (pgbouncer) matters at scale.",
        "analogy": "The steel filing cabinet everything important goes into.",
        "pitfalls": "No connection pooling, unindexed foreign keys, using SELECT * on wide tables, ignoring VACUUM/bloat.",
        "related": ["SQL", "pgvector", "MVCC", "Read replicas"],
    },
    "api gateway": {
        "term": "API gateway",
        "category": "architecture",
        "what": "A single entry point in front of backend services that handles routing, auth, rate limiting, and request shaping.",
        "why_matters": "Centralizes cross-cutting concerns so individual services don't reimplement auth and throttling; gives clients one stable address.",
        "beginner": "A hotel reception desk: every visitor goes through it, gets checked in, and is directed to the right room — guests never wander the staff corridors.",
        "advanced": "Handles TLS termination, JWT validation, rate limiting, canary routing, request/response transformation. Examples: Kong, Envoy, AWS API Gateway. Distinct from a service mesh (east-west traffic).",
        "analogy": "The front door with a receptionist.",
        "pitfalls": "Business logic creeping into the gateway, single point of failure without HA, latency from over-transformation.",
        "related": ["Microservices", "Rate limiting", "Load balancer", "Service mesh"],
    },
}


import re


def find_concepts(text: str) -> list[dict]:
    """Return library entries whose match phrase occurs in the text.

    Anchored at a word boundary with optional suffix, so 'rate limit' matches
    'rate limiting' but 'rag' does not match 'dragging'.
    """
    lower = text.lower()
    hits = []
    for phrase, entry in CONCEPTS.items():
        if re.search(r"\b" + re.escape(phrase) + r"\w*", lower):
            hits.append(entry)
    return hits
